sudo: false

language: php

cache:
  directories:
  - .Build/vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
- >
  composer require typo3/minimal:"$TYPO3";
  composer show;
- >
  echo;
  echo "Restoring the composer.json";
  git checkout .;

script:
- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;

- >
  echo;
  echo "Running the unit tests";
  composer ci:tests:unit;

- >
  echo;
  echo "Running the functional tests";
  composer ci:tests:functional;

jobs:
  include:
  - stage: test
    php: "7.2"
    env: TYPO3=^8.7
  - stage: test
    php: "7.1"
    env: TYPO3=^8.7
  - stage: test
    php: "7.0"
    env: TYPO3=^8.7
  - stage: test
    php: "7.2"
    env: TYPO3=^7.6
  - stage: test
    php: "7.1"
    env: TYPO3=^7.6
  - stage: test
    php: "7.0"
    env: TYPO3=^7.6
  - stage: release to ter
    if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
    php: "7.0"
    before_install: skip
    install: skip
    before_script: skip
    script:
    - >
      echo;
      echo "Preparing upload of release ${TRAVIS_TAG} to TER";
      echo;
      echo;
      composer global require helhum/ter-client;
    - >
      TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
      echo;
      echo "Uploading release ${TRAVIS_TAG} to TER";
      echo;
      echo;
      $HOME/.composer/vendor/bin/ter-client upload csv_to_openimmo . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
